### ISSUE TITLE
Update Simdjson when parser reallocation bug is fixed.

### ISSUE THREAD

**Issue by ajmikals** [didclab/CClient#1]
Simdjson has a bug (https://github.com/simdjson/simdjson/issues/938) in which the parser fails to reallocate its buffer when parsing documents beyond the first. For now, multiple parsers can be used to avoid this issue. When the bug is fixed, simdjson needs to be updated and a small refactor will be needed so that the same parser is reused.

**Comment by lemire** [comment]
Fix is upcoming and will be part of release 0.4.

**Comment by lemire** [comment]
Version 0.4 has been out for some time. Consider updating.

**Comment by ajmikals** [comment]
Thanks for letting me know.
